name: WaterQuest
options:
  bundleIdPrefix: com.waterquest
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: WaterQuest/Supporting/Info.plist
    CODE_SIGN_STYLE: Automatic
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  WaterQuest:
    type: application
    platform: iOS
    sources:
      - WaterQuest
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.waterquest.hydration
        PRODUCT_NAME: WaterQuest
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        CODE_SIGN_ENTITLEMENTS: WaterQuest/Supporting/WaterQuest.entitlements
